### ISSUE TITLE
StyleFire

### ISSUE THREAD

**Issue by profezzorn** [profezzorn/ProffieOS-StyleEditor#1]
P.S. The Style Fire breakout on the right side still has a typo for Speed, it says SEEED

Also, speaking of StyleFire, I don't think the "Config during Clash" section is affecting anything. Changing the cooling to 10000 should be shutting the fire totally off, but nothing different happens. High intensity numbers also do not affect anything.
I was trying to have a 200ms clash "suck up" all the fire power as an effect, but can't do it.
"Config during Lockup" does work as expected though. 

Read more: http://therebelarmory.com/thread/11874/style-editor-3-beta?page=1#ixzz6EQdyW1sq

**Comment by NoSloppy** [comment]
Just a friendly reminder:)

**Comment by profezzorn** [comment]
Looks like I made some changes to how clash works in the style editor and forgot to update StyleFire.
Should be fixed now.
