### ISSUE TITLE
Variation request: default "color wheel" value field

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#10]
Currently, the Variant field applies if using ColorChange in the blade style. Cool.
Could we also have a Variation value box? 
This way when using RotateColorsX<Variation<>, COLOR>.... the color would shift accordingly.
This could aid in editing the presets.ini file directly as well, and vice versa, retrieving the Variation value from the file and applying it in the editor.

**Comment by profezzorn** [comment]
Variant and Variation is the same thing.
The color wheel doesn't have a separate value, it's just a different mode for the same thing.

**Comment by NoSloppy** [comment]
Sorry,  
If blade powered on, stock "color wheel" colorchange mode entered, rotate and save, writing the variation to presets.ini.
Could you clarify how I would enter the written Variation, say Variation=12345 in style editor?
