### ISSUE TITLE
Slow...sort of.

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#12]
Slow _does_ show the yellow highlighting in slow-mo, but the blade animation just sort of jumps from one look to another, there's no actual slow blast wave or anything.
Would be useful when timing some rapid succession effects, like this blast I'm working on making more visible, less diffused by transparency:

Layers<
  Red,
TransitionEffectL<TrConcat<TrInstant,Strobe<GreenYellow,Black,20,30>,TrDelay<50>,AlphaL<Red,Int<6000>>,TrJoinR<TrWipe<50>,TrWipeIn<50>,TrConcat<TrInstant,AlphaL<Black,Int<16000>>,TrSmoothFade<300>>>>,EFFECT_BLAST>,
  BlastL<Cyan,400,250,401>>

**Comment by profezzorn** [comment]
That's not really what "slow" does though.
Slow is just meant to provide snapshots of rapidly moving things so you can see what they look like without that movement.

I think we would need something else if we want to actually slow things down.

**Comment by NoSloppy** [comment]
> I think we would need something else if we want to actually slow things down.

In my mind, that's what it would be. "Slow motion"

**Comment by profezzorn** [comment]
Slow wasn't working very well.
I made it an actual slow motion. (120x slowdown)
Might need to tweak it a bit, 120x is very very slow....

**Comment by NoSloppy** [comment]
> Might need to tweak it a bit, 120x is very very slow....

Indeed. `framesPerUpdate = on ? 10 : 0` seems pretty good? As in:
```
var slowState = new SavedState("slow", false, (on) => { framesPerUpdate = on ? 10 : 0; time_factor = framesPerUpdate == 0 ? 1000 : (500/framesPerUpdate)});
```

**Comment by NoSloppy** [comment]
Although also, everything normal speed is now sped up.

**Comment by profezzorn** [comment]
Really?
Hmm, I'll have to take a look at that.

**Comment by NoSloppy** [comment]
https://youtu.be/Fofs6uIIdfU

**Comment by profezzorn** [comment]
Should be fixed now.
