### ISSUE TITLE
Loading IgnitionDelay and RetractionDelay get "stuck"

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#124]
There's a long pause when clicking these buttons, and in the Dev tools window you can see it's PARSING over and over and over again. 
It does eventually stop, but I don't know what the problem is.

**Comment by NoSloppy** [comment]
It might be something with EASYBLADE?

**Comment by NoSloppy** [comment]
here's the weird log:
https://pastebin.com/aAtfXPpT

**Comment by NoSloppy** [comment]
Also, weird spark in emitter even though power is off.
Seems to be InOutHelper.
InOutHelper<EasyBlade<OnSpark<Green>,White>,300,800>

![Screenshot 2023-12-17 at 1 34 44 PM](https://github.com/profezzorn/ProffieOS-StyleEditor/assets/53964195/ab3578e5-f666-49a3-b4f9-2ec7ab6f45fc)

**Comment by profezzorn** [comment]
> Also, weird spark in emitter even though power is off.
Separate issue?

**Comment by NoSloppy** [comment]
True.

**Comment by profezzorn** [comment]
I think the problem is this line:
https://github.com/profezzorn/ProffieOS-StyleEditor/blob/89ac231498e5c3c55455fc8e7f4dab1a24a69cef/style_editor.html#L2180

**Comment by profezzorn** [comment]
Now I just need to figure out why I changed that, if it's required, and/or a faster way to do it. :)

**Comment by profezzorn** [comment]
So, I removed the DOCOPY(), which speeds things up a lot.
Not sure why I put it there, so keep an eye out for any problems that might pop up with macros...
