### ISSUE TITLE
Really Long URLs can't be entered/copied/shared

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#15]
Trying to resolve a very long 7172 character style's URL causes :
fredrik.hubbe.net unexpectedly closed the connection.
To recreate, put this style in the style box, (https://pastebin.com/eJxw93GP) submit, all works fine in the Editor.
Clicking the top most level in the right column populates the address bar with the entire string, which doesn't resolve if entered, nor if copied and pasted into a new browser window, and even TinyURL doesn't like it.

Is it possible to make a "share" sort of button that generates a more friendly URL and copies to the clipboard?

**Comment by profezzorn** [comment]
I kind of feel like this is a "don't do that" sort of problem, but I will look into it.

**Comment by NoSloppy** [comment]
I understand, but what would you suggest as a way to redirect someone with a link to "how it looks" in the Style Editor then?

**Comment by profezzorn** [comment]
I would find a way to make the URL shorter. 7k+ characters is just too much to be practical.
But like I said, I will look in to it.

**Comment by NoSloppy** [comment]
Any online URL Shortener can be used. Closing.
