### ISSUE TITLE
BladeAngle typo

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#16]
I think the second entry should be "What angle returns 32768", not also zero?
![Screen Shot 2021-01-28 at 10 08 25 PM](https://user-images.githubusercontent.com/53964195/106226568-80a1e300-61b5-11eb-91fe-bea53d72edf9.jpg)

**Comment by NoSloppy** [comment]
Still needs fix.

**Comment by profezzorn** [comment]
Looks like this has been fixed.
