### ISSUE TITLE
Request: Slider for Variation

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#17]
Could the Variation be put on a slider, like the way the Volume slider on the WebUSB page works? 
This would make it more friendly to seeing changes throughout the whole range as opposed to typing in values. The buttons only really help when using a ticked ColorChange in the bladestyle.

**Comment by profezzorn** [comment]
I should probably do the same kind of detection that I use to switch between ticked and non-ticked color wheel on the actual saber.

**Comment by NoSloppy** [comment]
Even better!

**Comment by NoSloppy** [comment]
PR #61
