### ISSUE TITLE
Request to add "Error: Transparent base color"

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#19]
The editor is forgiving on this, but code doesn't compile due to "Conversion from RGBA_nod to OverDriveColor"

**Comment by NoSloppy** [comment]
Reviving this as possibly pretty important.
Can it detect if the base layer contains transparency and throw an error ?

**Comment by profezzorn** [comment]
Done (on Copy)

**Comment by NoSloppy** [comment]
I commented on the merged commit as I forgot this issue was filied here.
Not sure if you'd see that so I'll paste here and add to it.

This seems to work only if the entire style is comprised of JUST a transparent color and you attempt to do Copy().
It will still allow something like this though:
`Layers<AlphaL<Red,Int<16000>,Green>>`

or something weird like 2 layers of solid colors over transparent layers. (this was generated by the Copy button):
```cpp
StylePtr<Layers<
  AlphaL<Red,Int<16000>>,
  ResponsiveBlastFadeL<White>,
  ResponsiveStabL<White>,
  Red,
  Green,
  InOutTrL<TrWipe<300>,TrWipeIn<500>>>>()
  ```
