### ISSUE TITLE
Error message specificity

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#2]
Is it possible to have the cause of an error in the style be highlighted in addition to the error message? And/or have the error message specify which layer? Sometimes hitting submit again puts the cursor in the right spot it seems, ( Is that an actual feature? ) Other times I can't find the cursor at all. 
TransitionEffectL:Expected EFFECT for argument 2 (EFFECT)
is a bit tough to locate without some guidance.
Since the right hand column is kind enough to number the layers, perhaps the error could be something like:
/*Layer 11*/ TransitionEffectL:Expected EFFECT for argument 2 (EFFECT) instead.
I realize it can't zero in on a missing > or comma in the middle of a line really,

**Comment by profezzorn** [comment]
It now highlights errors.
