### ISSUE TITLE
Reverse stripes are strange

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#22]
When reverse direction, the blend between colors seems incorrect. Hard to explain, but instead of blue into green for example, when the green should start coming out of the emitter, the blue is fading to dark first , then suddenly the green appears.
When normal direction (from tip) this does not occur.
Tried multiple browsers and it persists.
Video of both directions:
https://www.youtube.com/watch?v=SOXj4NO8cA4

**Comment by profezzorn** [comment]
Should be fixed now.
