### ISSUE TITLE
Would be cool to replace the preview cylinder 3D model with a nice Graflex 3D model

### ISSUE THREAD

**Issue by ShtokyD** [profezzorn/ProffieOS-StyleEditor#26]
I made a nice low-poly Graflex 3D-model some time ago, so we can try to make a nicer preview of the lightsaber with different materials and reflextions.

**Comment by NoSloppy** [comment]
:)

**Comment by profezzorn** [comment]
This was done a while ago....
(Although it hasn't been pushed live yet.)
