### ISSUE TITLE
Next version: "copy" button append a comma as well?

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#28]
Appending a comma would work for pasting the style into any position in a preset.
Pros:
-  less errors due to users just pasting and going
- Encourages using the "message" at the end as opposed to just NULL
- Still won't error if NO "message" used as in `>(),}`
Cons:
- Anyone accustomed to how it works now needs a little adjusting.

**Comment by profezzorn** [comment]
No, if we do that people will never learn or understand.
