### ISSUE TITLE
Gradient as a Stripes color doesn't work

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#29]
Assuming that Gradient isn't scalable with existing code (although OS6 Remap might do it)
It currently disregards size, therefore speed as well.
Example:
Stripes<3000,300,Gradient<Red,Black,Black,Black>,Blue>

**Comment by profezzorn** [comment]
What?
What doesn't work?
What happens?
How should it work?

**Comment by NoSloppy** [comment]
Oh. Well, the gradient isn't "compressed" into one of the stripes if it's a color in the list. Although like I said, maybe that's expected or incorrect assumption of behavior.

In the example above, the emitter area is red, then black to the tip, while blue sections @3000 wide alternate with :nothing" where the background gradient shows through.
Pic to explain current:
![Screen Shot 2022-01-21 at 10 33 47 PM](https://user-images.githubusercontent.com/53964195/150623366-8574e4b1-9f0e-4913-9e3f-017ca555eab0.jpg)

would expect something more like this, where the gradient is considered a stripe:
![Screen Shot 2022-01-21 at 10 36 33 PM](https://user-images.githubusercontent.com/53964195/150623369-7f5abf04-ae3d-4c41-afc8-965328a76772.jpg)

**Comment by profezzorn** [comment]
Stripes aren't made up of small blades, so it won't compress the gradients (or any other style). This is working as intended.

**Comment by NoSloppy** [comment]
Cool. Thanks.
