### ISSUE TITLE
Buttons and their locations

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#3]
Summary: Isn't there plenty of room to go back to toggleable buttons for Lockup, Drag, Melt, and LB?
The drop down menu works, but it feels out of place and awkward to use, plus there's space available...?
Here's a pic showing what, in my opinion, would be a sensible conducive layout: ( I see no way to insert an image, and the link redirects back to Github? You'll need to copy the URL manually)
[https://i.imgur.com/UvSMuwz.jpg](url)

I think it would be a good idea from a familiarity and a workflow perspective to move the submit button to the right end, and possibly sized up a bit?
The mouse flow is from all the way on the right column to choose a value to edit, then to the opposite side of the screen to edit a left justified value. At that point the next common movement would be back toward the right to head over and reselect the entire style again by clicking the outermost box of the column. If the submit button were "on the way there" It would make it more natural I feel (after doing this many times again and again.)

Also, now with the multi-line field for the style, hitting the Enter key is a line-feed and doesn't "enter" the edited value. Tab seems browser-tied to the next available field, so at the moment the submit button is the only option....unless Shift-click or something could be used. Thanks for listening, here's a pic

**Comment by profezzorn** [comment]
Link doesn't work.

**Comment by profezzorn** [comment]
Maybe I can make it so that if the cursor is at the very end, and you press enter, it submits.
Otherwise, I would think that tab and then enter would be a pretty good way to submit.

**Comment by profezzorn** [comment]
Got the image to work.
The amount of space available depends a lot on the size, shape and zoom level of the screen used.
I'm not sure why having the submit button on the right is better really. And making it flow to the right makes it farther away from the thing that it actually submits...

**Comment by NoSloppy** [comment]
If there can be a keyboard equivalent to submit, it wouldn't matter where the button goes anymore I suppose.
I just figured that most had become accustomed to it's location at the right side of the box, where it has lived until ProffieOS4.7.

**Comment by NoSloppy** [comment]
Tab and spacebar works as keyboard shortcut to hit Submit. Other is now non-issue stuff. 
Cleaning up here, closing this.
