### ISSUE TITLE
Request. Ability to adjust background actions

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#43]
Maybe we could toggle on/off the swinging, such that having a layer that uses SwingSpeed stuff wouldn't constantly show on a loop.
Also, an input field to adjust the WavLen value used.

**Comment by profezzorn** [comment]
Not sure what you mean. Also, this is two requests in one issue. Please open another one for the wavlen stuff, and provide an example or two for each request.

**Comment by NoSloppy** [comment]
Sure, sorry.
For this, I'm referring to the way there's always a swing action running on Sin.
So if we have 
```
Layers<
  Red,
  AlphaL<White,SwingSpeed<400>>>
  ```
  we see a Red blade with White fading in and out repeatedly because there's a swing motion baked into the running blade display. 
  Request is for something like a "Swinging emulation On/Off" checkmark that could control that feature.
  Else, we could leave it as is and just temporarily comment out the layer that uses SwingSpeed easily enough.

**Comment by NoSloppy** [comment]
Submitted PR
