### ISSUE TITLE
Request - priority BendTimePowX

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#44]
When it comes time to update, could this be one of the first things to figure out how to implement? It was on the request list for so long, and well worth the wait, but now it's time to play!
Unlike lots of other stuff, I feel this in particular is VERY trial and error based without seeing results from different values being plugged in. It would be a tremendous time saver for learning how it actually works and getting the desired result dialed in.
Documentation helps, but something a little less "mathy" to make it more tangible would be great. :)

**Comment by profezzorn** [comment]
Done.

**Comment by NoSloppy** [comment]
thanks!!
