### ISSUE TITLE
Invalid arguments could use error message

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#50]
Maybe it should generate an error message like "Expected XXX" when attempting to submit an invalid argument?
Example: `AudioFlicker<Red,Blue>`
If you click the right side column and select "Red", then click a Transition tab like `TrFade`, nothing happens. If you hit submit again, the Transition becomes the new whole thing alone, losing what you were working on. 
Is it possible for it to say "Expected COLOR" on the first attempt to submit the wrong kind of thing, and not wipe out the current style completely?

**Comment by profezzorn** [comment]
This particular wart should be fixed now.
