### ISSUE TITLE
LockupL - blue highlights missing from Lightning section

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#6]
**EDIT** I guess this is intentional, because the values are editable in the style box, but the changes don't take.
So editing Lightning is not possible?
Reproduce by:
Clicking the LockupL button, Check the Lockup section up top.
All changeable entries highlight in blue when clicked, and become editable in the style box.
However, everything in the Lightning block shape section, although clickable and editable, do not highlight in blue when selected.

**Comment by profezzorn** [comment]
Should be fixed now.
