### ISSUE TITLE
Percentage broken

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#62]
It's something in the "better comment handling" commit 71c28ed . Diff attached.
[diff.txt](https://github.com/profezzorn/ProffieOS-StyleEditor/files/11070781/diff.txt)

The Percentage button is doing nothing visually.
Manually entering `Percentage<WavLen<>,20>` throws the error:
`Percentage:Percentage:Missing > or ,`

Here is the previous, working version Style Editor's console when hitting Percentage button:
```html
PARSING: Percentage<RandomPerLEDF, 20>
Style Editor.html:7043 PARSING: RandomPerLEDF
Style Editor.html:7539 Percentage<RandomPerLEDF,20>
Style Editor.html:7043 PARSING: Percentage<RandomPerLEDF,20>
Style Editor.html:7043 PARSING: RandomPerLEDF
Style Editor.html:7340 Percentage<RandomPerLEDF,20>
Style Editor.html:7043 PARSING: Percentage<RandomPerLEDF,20>
Style Editor.html:7043 PARSING: RandomPerLEDF
```
But now we get a weird parsing of Mult involved:
`Mult<RandomPerLEDF,Int<6553.6>>`
```html
VM1868 style_editor.html:3639 Add effect 13 @ 0.8736328550757815
VM1868 style_editor.html:7228 PARSING: Percentage<RandomPerLEDF, 20>
VM1868 style_editor.html:7228 PARSING: RandomPerLEDF
VM1868 style_editor.html:7228 PARSING: Mult<RandomPerLEDF,Int<6553.6>>
VM1868 style_editor.html:7420 Uncaught MyError {desc: 'Percentage:Percentage:Missing > or ,', begin_pos: 0, end_pos: 29}
```

**Comment by profezzorn** [comment]
Should be fixed now.
