### ISSUE TITLE
Add hover texts for buttons

### ISSUE THREAD

**Issue by profezzorn** [profezzorn/ProffieOS-StyleEditor#66]
Especially the middle row of buttons, "submit", "copy", "layerize", etc.

**Comment by NoSloppy** [comment]
What should this do? I'm about to submit a PR for styling updates....

**Comment by NoSloppy** [comment]
I've played with a few options. 
Assuming you want like a bolding of the font on hover, unfortunately this resizes the button slightly to accommodate the increases font size, so ALL the other buttons shift slightly and it's very distracting to the eye.
I tried adjusting for it using some scaled transformations, but have not found something that keeps things where they were and just changes the font.
What is your vision for this, and how would the "middle row" mentioned above be a little different?

**Comment by profezzorn** [comment]
What I want is tooltips, so that when you hover over a button, it shows a little popup that tells you what the button does.
I think the easy way to do this is to just set an alt text.

**Comment by NoSloppy** [comment]
Added

**Comment by NoSloppy** [comment]
Closing this in lieu of full revamp
