### ISSUE TITLE
trconcat without intermediate colors commit broke stuff

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#69]
Commit 342d87e. It looks like it's triggering the transitions inside the TrConcat, but not the actual start of TrConcat itself nor the TranistionEffeclL it's contained in.
The whole layer and TrConcat are only triggered if you quickly click before the longest transition finishes
A good example:
`TransitionEffectL<TrConcat<TrFade<300>,AlphaL<White,Bump<Int<0>,Int<8000>>>,TrFade<3000>>,EFFECT_CLASH>`

If you watch the yellow highlighting in the Structured View, TrFade<300> and TrFade<3000> are triggered first and simultaneously.

**Comment by profezzorn** [comment]
Does it work better now?

**Comment by NoSloppy** [comment]
With that example, yes. However you can't string together transitions without colors, which is the actual update, right?
This example:
`TransitionEffectL<TrConcat<TrFade<300>,TrFade<300>,TrFade<300>,AlphaL<White,Bump<Int<0>,Int<8000>>>,TrFade<3000>>,EFFECT_CLASH>`
gives this error:
`TrConcat:Expected COLOR but got TrFadeClass[id = 2585451] for argument 2 (COLOR1)`
