### ISSUE TITLE
TrColorcycle wrong num args?

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#72]
There's a mismatch somewhere between colorcycle.h template (MILLIS, START_RPM, END_RPM)
and the editor, where the editor takes only 2 arguments (START_RPM, END_RPM) 

I think the first is acting as MILLIS, and the second is END_RPM. In other words, start speed is *always* defaulted to zero, but shows as end RPM?
 I can’t tell what’s wrong exactly but I think something is amiss.

**Comment by profezzorn** [comment]
Fixed: https://github.com/profezzorn/ProffieOS-StyleEditor/commit/262464c696738d1520af5575f42ac491bb07a34e
