### ISSUE TITLE
Expand button makes the right column condense to one long string

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS-StyleEditor#9]
When there's no more expansion left the button greys out. Cool. However if it's pressed again anyway, it highlights with a blue border. At this point the next click on anything condenses the right column and page refresh is needed to work any further.

This is how to recreate the issue:
Choose base color for example, click Expand (even though nothing there to expand). Button will be grey but highlight blue when clicked.
Click on outermost bracket in right column to re-select entire style, condenses to text string only at the top of screen.
Right column gone until page refresh.

**Comment by profezzorn** [comment]
This particular way to cause this problem has been fixed, let me know if you find another one.
